name = input("Enter your name: ")
age = input("Enter your age: ")
roll_no = input("Enter your roll number: ")
phone_no = input("Enter your phone number: ")
#print ("Your name :",name, "Your age: ", age, "Your roll_no is :", roll_no, "Your phone_no is:", phone_no, sep='\n')
print("Your name is :", name)
print("Your age is :", age)
print("Your roll number is :", roll_no)
print("Your phone number is :", phone_no)
print(type(age))